     ## NGINX CORS
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Credentials' 'true';

CORS 설정 : 브라우저가 다른 출처의 API 호출을 허용하도록 응답 헤더를 추가해 주는 설정
