# 썸네일 생성을 위한 Nginx 이미지 필터 모듈 설정

        location ~ "^/photo/r(?<arg_width>\d+)x(?<arg_height>\d+)/(?<image>.+)$" {
                alias /web/photo.test.com/$image;
                set $width $arg_width;
                set $height $arg_height;
                if ($arg_width = "0") {
                    set $width "-";
                }
                if ($arg_height = "0") {
                    set $height "-";
                }
                image_filter resize $width $height;
                image_filter_interlace on;
                image_filter_jpeg_quality 95;
                image_filter_sharpen 90;
                image_filter_webp_quality 90;
        }

        location ~ "^/photo/c(?<width>\d+)x(?<height>\d+)/(?<image>.+)$" {
                alias /web/photo.test.com/$image;
                image_filter crop $width $height;
                image_filter_interlace on;
                image_filter_jpeg_quality 95;
                image_filter_sharpen 90;
                image_filter_webp_quality 90;
        }
